%YAML:1.0

# pixel/superpixel size
#pixelSize: 8
#sPixelSize: 3

pixelSize: 7
sPixelSize: 3

stereo: 1
iterations: 1
reSteps: [0, 4, 4, 4]
minLevel: 2

# energy weights
# appWeight: 200.0
appWeight: [200.0, 100.0, 200.0, 200.0]
regWeight: [500.0, 300.0, 500.0, 500.0]
lenWeight: 1000.0
sizeWeight: 1000.0

# stereo weights
# default values:
#   dispWeight: 2000.0
#   smoWeight: 0.2
#   priorWeight: 0.2
#   occPriorWeight: 15.0
#   hiPriorWeight: 5.0
#   inlierThreshold: 3

dispWeight: [6000.0, 5000.0, 3000.0, 3000.0]
smoWeight: [500, 500, 200, 200]
priorWeight: 0.2
occPriorWeight: [15, 15, 15, 15]
hiPriorWeight: [0.5, 0.5, 0.7, 0.7] 
inlierThreshold: 3
peblThreshold: [20, 30, 10, 10]
updateThreshold: 0.01
instantBoundary: 0

# best values:
#   dispWeight: 4000.0
#   smoWeight: 10
#   priorWeight: 0.2
#   occPriorWeight: 15.0
#   hiPriorWeight: 0.5
#   inlierThreshold: 3

nThreads: 1





